### ISSUE TITLE
how does it work pipEnabled and showPipButton ?

### ISSUE THREAD

**Issue by CarmenLexa** [darwin-morocho/flutter-meedu-player#29]
How can I configure the pip? I can't find any example

final MeeduPlayerController _controller_video = MeeduPlayerController(
      controlsStyle: ControlsStyle.primary,
      pipEnabled: true,
      showPipButton: true
  );

at app.meedu.player.MeeduPlayerPlugin.initPipConfiguration(MeeduPlayerPlugin.java:78)
E/flutter (11662): 	at app.meedu.player.MeeduPlayerPlugin.onMethodCall(MeeduPlayerPlugin.java:55)
E/flutter (11662): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (11662): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (11662): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (11662): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11662): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (11662): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (11662): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (11662): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11662): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (11662): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by darwin-morocho** [comment]
> How can I configure the pip? I can't find any example
> 
> final MeeduPlayerController _controller_video = MeeduPlayerController(
> controlsStyle: ControlsStyle.primary,
> pipEnabled: true,
> showPipButton: true
> );
> 
> at app.meedu.player.MeeduPlayerPlugin.initPipConfiguration(MeeduPlayerPlugin.java:78)
> E/flutter (11662): at app.meedu.player.MeeduPlayerPlugin.onMethodCall(MeeduPlayerPlugin.java:55)
> E/flutter (11662): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/flutter (11662): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/flutter (11662): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
> E/flutter (11662): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter (11662): at android.os.MessageQueue.next(MessageQueue.java:336)
> E/flutter (11662): at android.os.Looper.loop(Looper.java:174)
> E/flutter (11662): at android.app.ActivityThread.main(ActivityThread.java:7356)
> E/flutter (11662): at java.lang.reflect.Method.invoke(Native Method)
> E/flutter (11662): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> E/flutter (11662): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Sorry for the broken URL. please check https://darwin-morocho.github.io/flutter-meedu-player/#/picture-in-picture

**Comment by CarmenLexa** [comment]
Thanks it works, but the video is paused, how do I make it play when it is in miniature?

**Comment by darwin-morocho** [comment]
> Thanks it works, but the video is paused, how do I make it play when it is in miniature?

The autoplay in pip mode depends of each device it can be different in many devices
